### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by koconder** [Evengard/cntlm#15]
Same as the Sourceforge, CNTLM project seems dead. Newer OS's are starting have an array of issues.

**Comment by jschwartzenberg** [comment]
This fork is getting updates: https://github.com/versat/cntlm

I would suggest everybody to contribute to it!

**Comment by Evengard** [comment]
I actually am not really maintaining this project, I just forked it some time ago from Sourceforge to implement what I needed. It seems that this project is now the first found via Google. I updated the Readme to point to the updated fork, thanks.
